version: '3.8'
services:
  devcontainer:
    image: arulrajnet/vscode-pelican-devcontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
